"""Optional AI review layer for company research reports.

The deterministic report calculates numbers. This module only reviews the
structured output and renders a bounded Markdown section.
"""

from __future__ import annotations

import json
import os
from typing import Any

from pydantic import BaseModel, Field


DEFAULT_AI_MODEL = "gpt-4o-mini"

SYSTEM_PROMPT = """You are an AI research reviewer for a first-pass company research tool.

You review structured report data generated by deterministic Python calculations.

Rules:
1. Do not give buy, sell, or hold recommendations.
2. Do not provide price targets.
3. Do not predict short-term stock movement.
4. Do not invent numbers.
5. Use only the provided payload.
6. If the data is insufficient, say what needs manual verification.
7. Focus on reasoning quality, contradictions, beginner misreadings, and weak assumptions.
8. Keep the tone professional, plain-English, and concise.
9. Do not sound promotional.
10. Do not overstate confidence.

Your job:
- Summarize what the report actually says.
- Check whether the evidence supports the conclusion.
- Identify the biggest risks and weak assumptions.
- Explain what a beginner might misunderstand.
- Suggest what should be manually verified next.

Return structured output matching the provided schema."""


class AIReviewResult(BaseModel):
    analyst_summary: str = Field(..., description="Concise review of what the report says.")
    evidence_check: list[str] = Field(default_factory=list)
    main_risks: list[str] = Field(default_factory=list)
    possible_beginner_misreadings: list[str] = Field(default_factory=list)
    what_to_verify_next: list[str] = Field(default_factory=list)
    beginner_translation: str = Field(..., description="Plain-English translation for beginners.")
    confidence_note: str = Field(..., description="Data confidence and limitation note.")


def _compact(value: Any) -> Any:
    """Convert pandas/numpy values into JSON-friendly compact structures."""
    try:
        import pandas as pd
    except Exception:
        pd = None

    if pd is not None:
        if isinstance(value, pd.DataFrame):
            return value.where(pd.notna(value), None).to_dict(orient="records")
        if isinstance(value, pd.Series):
            return value.where(pd.notna(value), None).to_dict()
        if not isinstance(value, (list, tuple, dict)):
            try:
                if pd.isna(value):
                    return None
            except (TypeError, ValueError):
                pass

    if isinstance(value, dict):
        return {str(k): _compact(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_compact(v) for v in value]
    if hasattr(value, "item"):
        try:
            return value.item()
        except Exception:
            return value
    return value


def _pick(report_data: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: _compact(report_data.get(key)) for key in keys}


def build_ai_review_payload(report_data: dict[str, Any], depth: str = "basic") -> dict[str, Any]:
    """Build a compact payload from deterministic report data.

    The AI should receive evidence, not the final Markdown and not large raw
    data tables. Deep mode includes a little more context but still avoids raw
    price history and full statements.
    """
    base_keys = [
        "ticker",
        "benchmark",
        "version",
        "research_profile",
        "research_status",
        "one_line_verdict",
        "key_takeaways",
        "beginner_summary",
        "price_metrics",
        "growth_quality_metrics",
        "valuation_snapshot",
        "ruin_risk_metrics",
        "research_score",
        "score_components",
        "sanity_checks",
        "data_confidence",
        "manual_verification",
        "final_research_questions",
    ]
    payload = _pick(report_data, base_keys)
    payload["review_depth"] = depth

    if depth == "deep":
        payload["company_profile"] = _compact(report_data.get("company_profile"))
        payload["business_model_and_cash_flow"] = _compact(report_data.get("business_model_and_cash_flow"))

    return payload


def _user_prompt(payload: dict[str, Any]) -> str:
    return (
        "Review the following structured report data. Use only this payload. "
        "Return the structured AI review.\n\n"
        + json.dumps(payload, ensure_ascii=False, indent=2)
    )


def call_ai_review(
    payload: dict[str, Any],
    model: str = DEFAULT_AI_MODEL,
    timeout: int = 60,
    max_output_tokens: int = 1200,
) -> AIReviewResult | None:
    """Call OpenAI Chat Completions structured outputs.

    Any failure returns None. The caller can read call_ai_review.last_error for
    a human-readable reason.
    """
    call_ai_review.last_error = None  # type: ignore[attr-defined]

    if not os.getenv("OPENAI_API_KEY"):
        call_ai_review.last_error = "OPENAI_API_KEY not found."  # type: ignore[attr-defined]
        return None

    try:
        from openai import OpenAI
    except ImportError:
        call_ai_review.last_error = "openai package is not installed."  # type: ignore[attr-defined]
        return None

    try:
        client = OpenAI(timeout=timeout)
        completion = client.chat.completions.parse(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": _user_prompt(payload)},
            ],
            response_format=AIReviewResult,
            max_tokens=max_output_tokens,
        )
        review = completion.choices[0].message.parsed
        if isinstance(review, AIReviewResult):
            return review
        call_ai_review.last_error = "OpenAI response could not be parsed into the AI review schema."  # type: ignore[attr-defined]
        return None
    except Exception as exc:
        call_ai_review.last_error = f"{type(exc).__name__}: {exc}"  # type: ignore[attr-defined]
        return None


call_ai_review.last_error = None  # type: ignore[attr-defined]


def _bullets(items: list[str]) -> str:
    clean = [item.strip() for item in items if item and item.strip()]
    if not clean:
        return "- No specific item returned."
    return "\n".join(f"- {item}" for item in clean)


def render_ai_review_markdown(review: AIReviewResult | None, status_message: str | None = None) -> str:
    if review is None:
        return render_ai_review_skipped(status_message or "AI Review was not available.")

    return f"""## AI Review

This section is AI-assisted and uses only the generated report data above.
It is not investment advice, not a buy/sell recommendation, and not a price target.

### Analyst Summary

{review.analyst_summary}

### Evidence Check

{_bullets(review.evidence_check)}

### Main Risks

{_bullets(review.main_risks)}

### Possible Beginner Misreadings

{_bullets(review.possible_beginner_misreadings)}

### What to Verify Next

{_bullets(review.what_to_verify_next)}

### Beginner Translation

{review.beginner_translation}

### Confidence Note

{review.confidence_note}
"""


def render_ai_review_skipped(reason: str) -> str:
    return f"""## AI Review

AI Review was requested but skipped.

Reason: {reason}

The deterministic report was still generated successfully.
"""
